# This file's semantics are documented at
# https://docs.gitlab.com/ce/ci/yaml/README.html

default:
  image: snowdriftcoop/snowdrift-ci:0.0.6

variables:
  SD_STACK_ARGS: "--stack-root ${CI_PROJECT_DIR}/stack-root"
  POSTGRES_DB: snowdrift_test


stages:
  - deps
  - build and test
  - deploy

cache:
  key:
    files:
      - stack.yaml
  paths:
    - stack-root
  policy: pull


.deps-common:
  stage: deps
  script: stack ${SD_STACK_ARGS} test --only-dependencies
  cache:
    paths:
      - stack-root
    policy: pull-push

deps:
  extends: .deps-common
  only:
    changes:
      - stack.yaml

# deps only needs to be run when stack.yaml changes.  However, in some cases
# (the cache might have been deleted etc), it needs to be run even without
# changes to stack.yaml, so we allow it to be run manually.
deps-manual:
  extends: .deps-common
  when: manual

build and test:
  stage: build and test
  services:
    - postgres:9.3
  script:
    - PGUSER=postgres PGHOST=postgres stack ${SD_STACK_ARGS} test --fast

# Build for deploy, using --pedantic
.build-common:
  stage: build and test
  services:
    - postgres:9.3
  script:
    - PGUSER=postgres PGHOST=postgres DEPLOY=false ./ci-support/deploy
  # Don't force pedantry on people.
  allow_failure: true
  artifacts:
    paths:
      - SnowdriftReboot.keter

deploy-build:
  extends: .build-common

deploy-build for Ubuntu 14.04:
  extends: .build-common
  image: snowdriftcoop/snowdrift-ci:0.0.6-14.04
  # This job needs its own cache because of differences in libc.
  cache:
    key: "Ubuntu 14.04"
    policy: pull-push

deploy:
  stage: deploy
  cache:
    paths: []
  dependencies:
    - deploy-build
  script:
    - BUILD=false ./ci-support/deploy
  only:
    # Only deploy from master.
    #
    # This is not a security measure, since someone could push a branch that
    # changes this line. It's a convenience. Security is maintained by only
    # allowing production secrets to be sent to protected branches.
    - master@sd/snowdrift
  # The scheduled runs don't get deployed.
  except:
    - schedules
  when: manual
  environment:
    name: production
    url: https://snowdrift.coop
