# This file's semantics are documented at
# https://docs.gitlab.com/ce/ci/yaml/README.html

include:
  # This is the source of image variables used below.
  - local: '/ci-support/docker/images.yml'

default:
  # Source: ci-support/docker/image-build-centos-7
  image: "${image_build_centos_7}"

variables:
  SD_STACK_ARGS: "--stack-root ${CI_PROJECT_DIR}/stack-root"
  POSTGRES_DB: snowdrift_test

stages:
  - build and test
  - deploy

build and test:
  cache:
    key:
      prefix: "Centos 7"
      files:
        - stack.yaml.lock
    paths:
      - stack-root
  stage: build and test
  services:
    - postgres:9.3
  # | If this gets much longer, turn it into an external script.
  script:
    # Make sure stack/ghc picks up changes to template files.
    - touch website/src/Settings/StaticFiles.hs
    - PGUSER=postgres PGHOST=postgres stack ${SD_STACK_ARGS} test --fast

# Build for deploy, using --pedantic
.deploy-common:
  stage: build and test
  services:
    - postgres:9.3
  script:
    - PGUSER=postgres PGHOST=postgres DEPLOY=false ./ci-support/deploy
  # Don't force pedantry on people.
  allow_failure: true
  artifacts:
    paths:
      - SnowdriftReboot.keter

deploy-build for Centos 7:
  extends: .deploy-common
  cache:
    paths:
      - stack-root
    key:
      files:
        - stack.yaml.lock
      prefix: "Centos 7"

deploy-build for Ubuntu 14.04:
  extends: .deploy-common
  image: "${image_build_ubuntu_14_04}"
  cache:
    paths:
      - stack-root
    key:
      files:
        - stack.yaml.lock
      prefix: "Ubuntu 14.04"

deploy:
  stage: deploy
  # Source: ci-support/docker/image-deploy/Dockerfile
  image: "${image_deploy}"
  cache:
    paths: []
  dependencies:
    - "deploy-build for Ubuntu 14.04"
  script:
    - BUILD=false ./ci-support/deploy
  only:
    # Only deploy from master.
    #
    # This is not a security measure, since someone could push a branch that
    # changes this line. It's a convenience. Security is maintained by only
    # allowing production secrets to be sent to protected branches.
    - master@snowdrift/snowdrift
  # The scheduled runs don't get deployed. FIXME: Why do we even have a
  # scheduled run?
  except:
    - schedules
  when: manual
  environment:
    name: production
    url: https://snowdrift.coop
