# This file's semantics are documented at
# https://docs.gitlab.com/ee/ci/yaml/README.html

stages:
    - deps
    - build
    - test

deps:
    stage: deps
    script:
        # I did these steps manually on the system, since I'm using the shell
        # runner for now.
        #- apt-get --quiet update
        #- apt-get --quiet --assume-yes install curl postgresql libgmp-dev libpq-dev
        #- curl -sSL https://get.haskellstack.org/ | sh
        - stack clean
        - stack test --no-run-tests --only-dependencies --install-ghc

build:
    stage: build
    script:
        - touch website/src/Settings/StaticFiles.hs
        - stack build

test:
    stage: test
    script:
        - ./build.sh test
