# This file's semantics are documented at
# https://docs.gitlab.com/ee/ci/yaml/README.html

stages:
- deps
- build
- test

cache:
    paths:
    - .stack-work
    - .stack-test
    - "*/.stack-work"
    - website/.shakespeare-sass

deps:
    stage: deps
    only:
    - branches@sd/snowdrift
    script:
        # I did these steps manually on the system, since I'm using the shell
        # runner for now.
        #- apt-get --quiet update
        #- apt-get --quiet --assume-yes install curl postgresql libgmp-dev libpq-dev
        #- curl -sSL https://get.haskellstack.org/ | sh
        "stack test --no-run-tests --only-dependencies --install-ghc"

build:
    stage: build
    only:
    - branches@sd/snowdrift
    script:
    - "touch website/src/Settings/StaticFiles.hs"
    - "stack build"

test:
    stage: test
    only:
    - branches@sd/snowdrift
    script: "./build.sh test"
